AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 99

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - arrangement.gemspec

Metrics/MethodLength:
  Max: 16
